[package]
name = "y2025d10"
version = "0.1.0"
edition = "2021"

[lib]
path = "y2025d10.rs"

[dependencies]
good_lp = { version = "1.14.2", features = ["highs"], default-features = false }
itertools = "0.14.0"
